baseURL = "http://example.com/"
languageCode = "en-us"
title = "Kapchits"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1

[menu]

  [[menu.main]]
    name   = "Videos"
    url    = "/videos/"
    weight = 10

  [[menu.main]]
    name   = "User Agreement"
    url    = "/user-agreement/"
    weight = 20

  [[menu.main]]
    name   = "Teaching Materials"
    url    = "/teaching-materials/"
    weight = 30

  [[menu.main]]
    name   = "Supervisor Contact"
    url    = "/supervisor-contact/"
    weight = 40

  [[menu.main]]
    name   = "Scholars"
    url    = "/scholars/"
    weight = 50

  [[menu.main]]
    name   = "Projects"
    url    = "/projects/"
    weight = 60

  [[menu.main]]
    name   = "Privacy Policy"
    url    = "/privacy-policy/"
    weight = 70

  [[menu.main]]
    name   = "Photos"
    url    = "/photos/"
    weight = 80

  [[menu.main]]
    name   = "Links"
    url    = "/links/"
    weight = 90

  [[menu.main]]
    name   = "Lexicon"
    url    = "/lexicon/"
    weight = 100

  [[menu.main]]
    name   = "Kinship Terms"
    url    = "/kinship-terms/"
    weight = 110

  [[menu.main]]
    name   = "Grammar"
    url    = "/grammar/"
    weight = 120

  [[menu.main]]
    name   = "Faq"
    url    = "/faq/"
    weight = 130

  [[menu.main]]
    name   = "Course Syllabus"
    url    = "/course-syllabus/"
    weight = 140

  [[menu.main]]
    name   = "Contact"
    url    = "/contact/"
    weight = 150

  [[menu.main]]
    name   = "Conferences"
    url    = "/conferences/"
    weight = 160

  [[menu.main]]
    name   = "About"
    url    = "/about/"
    weight = 170
publishDir = "docs"
